# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: DAST

on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]
  workflow_dispatch:

jobs:
  DAST:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]        

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Installing pm2
      run:  |
        echo "Installing pm2 globally"
        npm install -g pm2@latest
    - name: run app
      run: |
        echo "Starting express server"
        pm2 start ./app.js
        echo "started express server, getting the response"
        curl curl http://localhost:3000/

    - name: OWASP ZAP API Scan        
      uses: zaproxy/action-api-scan@v0.2.0
      with:
        target: "http://localhost:3000"         
        allow_issue_writing: false
